<Project>

  <PropertyGroup>
    <Version>0.1.0</Version>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>JT</Authors>
    <Copyright>Copyright 2026 JT</Copyright>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>typesafe;ai;jev;system-one;llm;classification;judgment</PackageTags>
    <PackageProjectUrl>https://github.com/Hawxy/TypeSafeAI.Net</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

</Project>
